arktypeio/arktype

pnpm-lock.yaml, redo.dev/docusaurus.config.js, redo.dev/package.json, redo.dev/src/components/LoadingAnimation/LoadingAnimation.module.css, redo.dev/src/components/LoadingAnimation/LoadingAnimation.tsx, redo.dev/src/components/toolSummaries.tsx, redo.dev/src/css/custom.css, scripts/docgen/api/findUnusedExports.ts
Added LoadingAnimation with a scroll to the element 
Added GTag to allow for GA collection
=> redo.dev: add demo loading animation and gtag

.vscode/settings.json, dev/configs/.eslintrc.cjs, dev/scripts/testTsVersions.ts, dev/test/instanceof.test.ts, package.json
+ restrictions to eslint for ./src
=> test: upgrade ts morph and add previous version to test 

dev/configs/.changeset/new-boats-jump.md, dev/configs/.changeset/smart-toes-worry.md, dev/examples/type.ts, dev/test/array.test.ts, dev/test/narrow.test.ts, src/traverse/problems.ts, src/traverse/traverse.ts
=> fix: ensure array elements are exhaustively checked by default

README.md, dev/arktype.io/copyCNAME.ts, dev/arktype.io/docs/api.mdx, dev/arktype.io/docs/demos/generated/demo.css.ts, dev/arktype.io/docs/demos/generated/populateDemo.ts, dev/arktype.io/docs/demos/layout/demo.css, dev/arktype.io/docs/demos/layout/populateDemo.ts, dev/arktype.io/docs/index.mdx, dev/arktype.io/package.json, dev/arktype.io/tsconfig.json, dev/scripts/copyCNAME.ts, dev/scripts/docgen/main.ts, dev/scripts/docgen/mapDir.ts, dev/scripts/docgen/snippets/extractSnippets.ts, dev/scripts/docgen/snippets/transformTsFileText.ts, dev/scripts/docgen/snippets/writeSnippets.ts
closes [StackBlitz morphs display undefined as output](https://github.com/arktypeio/arktype/issues/773)
=> docs: fix a bug causing morph output to display as undefined in StackBlitz, improve highlighting

ark/type/src/parser/objectLiteral.ts, ark/type/src/parser/shared.ts, ark/type/src/parser/tuple.ts, ark/type/test/array.test.ts, ark/type/test/objectLiteral.test.ts
=> feat: symbolics keys with added optional to definition, optional tuples

dev/configs/.changeset/heavy-melons-approve.md, dev/test/morph.test.ts, src/scopes/type.ts
=> fix: extracted morph inference

README.md, dev/configs/.changeset/beige-schools-guess.md, src/scopes/cache.ts, src/scopes/scope.ts
This change should have essentially no external impact.
Resolves https://github.com/arktypeio/arktype/issues/900
=> fix: don't freeze definitions for compatibility with sass

.changeset/foo-bar-baz.md, .changeset/giant-rivers-drop.md, ark/schema/shared/intersections.ts, ark/type/CHANGELOG.md, ark/type/__tests__/divisor.test.ts, ark/type/__tests__/keyof.test.ts, ark/type/__tests__/pipe.test.ts, ark/type/__tests__/realWorld.test.ts, ark/type/package.json, ark/util/registry.ts
=> fix some shallowly discriminated unions

README.md
hey, was exploring the lib and found that the tests link is stale
=> fix tests link in readme

ark/attest/CHANGELOG.md, ark/attest/README.md, ark/attest/bench/bench.ts, ark/attest/cache/ts.ts, ark/attest/cache/utils.ts, ark/attest/package.json, ark/type/__tests__/cyclic.bench.ts, ark/type/__tests__/object.bench.ts, ark/type/__tests__/operand.bench.ts, ark/type/__tests__/operator.bench.ts, package.json
=> fix(attest): improve bench extraction, add docs on baseline expression

ark/repo/scratch.ts, ark/type/__tests__/generic.test.ts, ark/type/__tests__/submodule.test.ts, ark/type/package.json, ark/type/scope.ts
=> fix: scoped BoundModule inference

README.md, ark/attest/package.json, ark/fs/package.json, ark/schema/package.json, ark/type/package.json, ark/util/package.json, ark/util/registry.ts
=> chore: bump versions

ark/attest/__tests__/snapExpectedOutput.ts, ark/attest/__tests__/snapTemplate.ts, ark/util/serialize.ts
=> feat: Symbolic key snapshotting in attest

ark/attest/package.json, ark/fs/package.json, ark/repo/scratch.ts, ark/schema/constraint.ts, ark/schema/node.ts, ark/schema/package.json, ark/schema/roots/union.ts, ark/schema/structure/structure.ts, ark/type/__tests__/discrimination.test.ts, ark/type/package.json, ark/util/package.json, ark/util/registry.ts
=> fix: discriminated unions of objects with undeclared key handling

ark/schema/roots/root.ts, ark/type/__tests__/pipe.test.ts
=> fix: preserve morphs on more piped properties

ark/attest/__tests__/unwrap.test.ts, ark/attest/assert/attest.ts, ark/attest/assert/chainableAssertions.ts, ark/attest/package.json, ark/fs/package.json, ark/repo/ts.js, ark/schema/package.json, ark/schema/roots/root.ts, ark/schema/shared/errors.ts, ark/schema/shared/standardSchema.ts, ark/type/__tests__/standardSchema.test.ts, ark/type/methods/base.ts, ark/type/package.json, ark/util/package.json, ark/util/registry.ts, package.json
=> feat: update to latest standard-schema

ark/attest/package.json, ark/fs/package.json, ark/schema/package.json, ark/type/attributes.ts, ark/type/package.json, ark/util/package.json, ark/util/registry.ts
=> fix: replace unique symbols with noSuggest

ark/docs/components/AutoDocs.tsx, ark/docs/content/docs/auto.mdx
https://github.com/user-attachments/assets/a8def3d6-5321-4d99-9cd2-bae210b43138
for #1216 
a starting point for the autodocs :)
=> feat(docs): autogenerated table for keywords

ark/docs/app/layout.tsx
=> fix(theme): default to dark and disable system default

ark/attest/package.json, ark/fast-check/package.json, ark/fs/package.json, ark/repo/scratch.ts, ark/schema/__tests__/errors.test.ts, ark/schema/__tests__/unit.test.ts, ark/schema/config.ts, ark/schema/constraint.ts, ark/schema/node.ts, ark/schema/package.json, ark/schema/parse.ts, ark/schema/predicate.ts, ark/schema/roots/basis.ts, ark/schema/roots/union.ts, ark/schema/shared/declare.ts, ark/schema/shared/errors.ts, ark/schema/shared/implement.ts, ark/schema/shared/traversal.ts, ark/schema/structure/prop.ts, ark/schema/structure/required.ts, ark/schema/structure/structure.ts, ark/type/__tests__/config.test.ts, ark/type/__tests__/thunk.test.ts, ark/type/package.json, ark/util/package.json, ark/util/records.ts, ark/util/registry.ts, ark/util/traits.ts, package.json
=> feat: node-level expected, actual, problem and message writer config

ark/docs/app/layout.tsx, ark/docs/app/providers.tsx, ark/docs/package.json
deployed here: https://ark-posthog.netlify.app
charts from my first clicks around:
=> feat(docs): web analytics from posthog

ark/attest/package.json, ark/fs/package.json, ark/repo/scratch.ts, ark/schema/package.json, ark/schema/structure/structure.ts, ark/type/CHANGELOG.md, ark/type/__tests__/defaults.test.ts, ark/type/package.json, ark/util/package.json, ark/util/registry.ts
Fix a jitless-mode bug causing default + `onUndeclaredKey` transformations to not apply.
Closes #1335
=> fix jitless object transformations

.gitignore, ark/attest/package.json, ark/fs/package.json, ark/repo/scratch.ts, ark/repo/scratch/fn.ts, ark/schema/package.json, ark/schema/shared/errors.ts, ark/schema/structure/structure.ts, ark/type/CHANGELOG.md, ark/type/__tests__/match.test.ts, ark/type/__tests__/realWorld.test.ts, ark/type/match.ts, ark/type/package.json, ark/util/package.json, ark/util/registry.ts, tsconfig.json
=> fix a rare jitless crash, experimental string matching

ark/attest/package.json, ark/fs/package.json, ark/schema/package.json, ark/schema/roots/root.ts, ark/type/CHANGELOG.md, ark/type/__tests__/cyclic.bench.ts, ark/type/__tests__/expressions.test.ts, ark/type/__tests__/match.bench.ts, ark/type/__tests__/object.bench.ts, ark/type/__tests__/operand.bench.ts, ark/type/__tests__/operator.bench.ts, ark/type/__tests__/pipe.test.ts, ark/type/package.json, ark/type/parser/ast/infer.ts, ark/type/parser/ast/validate.ts, ark/type/parser/reduce/dynamic.ts, ark/type/parser/reduce/shared.ts, ark/type/parser/reduce/static.ts, ark/type/parser/shift/operator/operator.ts, ark/type/parser/tupleExpressions.ts, ark/util/package.json, ark/util/registry.ts
=> to operator (|>) string syntax

ark/docs/components/apiData.ts, ark/docs/content/docs/configuration/index.mdx
=> docs: fix links

ark/docs/content/docs/integrations/index.mdx
Hello, I was working on a RHF and notice the issue for the resolver `User` was wrong and also added some helper note in case user create their custom input using `useController` 
let me know if this ok or need to update something, if no please discard the changes
Thank you :)
=> docs: updating rhf integration

ark/schema/shared/traversal.ts, ark/type/__tests__/pipe.test.ts
=> add complex pipe tests
