arktypeio/arktype

- arktype.io/src/pages/index.tsx
- arktype.io/src/theme/Root.js
- pnpm-lock.yaml
- redo.dev/docusaurus.config.js
- redo.dev/package.json
So the last branch was maybe merged a bit too fast KEK
- Redo.dev I copied the dependencies over from arktype and it works POG
- Swizzle needed. it looks gross when building without it
- <Animation/> is a component now
> fix: redo.dev dev build

- README.md
This PR change the example of `deno` usage.
> docs: fix typo on `deno` import example

- src/parse/definition.ts
This fixes the discussed problem with `typescript@5.1.0-dev.20230311` but I'm not entirely sure if it's the correct fix for everything. I wonder what your tests might tell about it.
> fix: make `validateDefinition` non-distributive

- dev/configs/.changeset/tricky-terms-worry.md
- dev/test/record.test.ts
- src/traverse/traverse.ts
> fix: check all keys when in strict or distilled mode, even if one fails

- dev/test/keywords.test.ts
- src/scopes/validation/validation.ts
Fixes #743
This commit adds an additional check to the `parsedInteger` validator, using `Number.isSafeInteger()` to require that any parsed integer has maximum precision (cannot overflow). This better represents what the average user would want, but may fail on some valid inputs. An `unsafeParsedInteger` validator should be considered in the future.
Due to many upcoming changes to error scopes, 'string' was used as the base type and the regex check was made in the narrow. The error message when a non-string is passed has changed slightly, just saying "must be a string" instead of "must be a well-formed integer string." This is a very minor change and can be dismissed.
BREAKING CHANGE: Any unsafe integers that use the `parsedInteger` validator will now fail the validation.
> feat: only allow safe-precision integers to pass `parsedInteger`

- dev/arktype.io/src/components/autoplayDemo.tsx
- dev/arktype.io/src/components/contents.tsx
- dev/arktype.io/src/components/features.tsx
- dev/arktype.io/src/components/homeDemo.tsx
- dev/arktype.io/src/components/installationBlock.tsx
- dev/arktype.io/src/css/custom.css
Hi I found some bugs on the site so I fixed that.
- Fixed the floating div that didn't have enough space when scrolling.
- Added side spacing on mobile view.
- Added animaitons for logo and text in navbar.
> docs: website margin improvements

- .github/semantic.yml
- ark/dark/color-theme.json
Adds some extra scopes and highlight rules, as follows:
- `meta.function-call` and `support.function`
- This adds function highlighting for Python and Ruby, respectively
- `meta.function-call.arguments`
- Prevents function arguments getting highlighting as functions in Python
- `constant.character.escape`
- Highlight escape sequences in Python, such as `\n`, `\t`, etc.
- `entity.name.tag`
- Better highlighting for `.yml` file keys
- `support.type.exception`
- Highlighting exceptions in Python as a type
I haven't extensively tested this, but the above does seem to be working correctly and I haven't noticed any side-effects in ts/js files in my limited experimenting.
Some examples:
Before
After
> feat: improve highlighting for python, yml, and ruby

- ark/dark/color-theme.json
Fixes highlighting of decorators inside classes in python files. Also made sure this didn't break highlighting of decorators outside of functions, which it doesn't.
Before:
After:
> fix: correctly highlight decorators in classes as well as in global scope

- dev/configs/.changeset/beige-snails-wash.md
- dev/test/intersection.test.ts
- dev/test/morph.test.ts
- dev/test/scope.test.ts
- src/parse/ast/intersection.ts
Unfortunately, some cross-scope operations will still result in an error at runtime. You will know at build time if this occurs by a message in an intersection like "Unable to resolve alias 'myExternalAlias'". The workaround is to use the in-scope type parser as follows until next release for these scenarios:
Unions:
```ts
const $ = scope({
a: "'abc'",
b: { "c?": "a" }
})
const types = $.compile()
// This fails if you don't use scoped type for now, fixing in next release
const t = $.type([types.b, "|", { extraProp: "string" }])
```
Intersections:
```ts
const $ = scope({
a: "'abc'",
b: { "c?": "a" }
})
const types = $.compile()
// This fails if you don't use scoped type for now, fixing in next release
const t = $.type([types.b, "&", { extraProp: "string" }])
```
> fix: intersection inference across scopes

- dev/configs/.changeset/many-tools-doubt.md
- dev/test/morph.test.ts
- src/parse/ast/ast.ts
> fix: inference failure for certain recursive unions

- dev/configs/.changeset/unlucky-kangaroos-divide.md
- dev/test/discriminate.test.ts
- src/nodes/compose.ts
- src/nodes/discriminate.ts
- src/nodes/rules/props.ts
> fix: ensure optional paths are not used as discriminants

- dev/configs/.changeset/pretty-dogs-film.md
- dev/test/astUtils.test.ts
- src/parse/ast/utils.ts
Improves astToString, some examples:
Before
After
> feat: improve astToString, add tests for astToString

- .github/actions/setup/action.yml
- .github/workflows/pr.yml
- dev/configs/.changeset/fast-onions-boil.md
- dev/test/instanceof.test.ts
- dev/test/morph.test.ts
- src/parse/ast/intersection.ts
- src/parse/ast/morph.ts
- src/scopes/ark.ts
- src/utils/generics.ts
> fix: allow instanceof abstract classes, avoid inferring some function props as morphs

- ark/attest/__tests__/benchExpectedOutput.ts
- ark/attest/__tests__/benchTemplate.ts
- ark/attest/__tests__/utils.ts
- ark/attest/bench/type.ts
- ark/attest/tsserver/tsserver.ts
- ark/repo/tsup.config.ts
resolves https://github.com/arktypeio/arktype/issues/884
Changes:
* type bench VFS env now uses `createFSBackedSystem` System object in order to have access to external modules
* unit test added / snapshot updated
* adds "ESM" build target in ark/repo/tsup.config.ts
> fix: type bench can access external modules

- dev/attest/src/assertions.ts
- dev/attest/src/bench/type.ts
- dev/attest/src/caller.ts
- dev/attest/src/type/internal/getAssertionsInFile.ts
This PR fixes some typos. I found a few typos by [VS Code typos extension](https://marketplace.visualstudio.com/items?itemName=tekumara.typos-vscode) and https://github.com/crate-ci/typos.
>  refactor: fix some typos

- ark/type/__tests__/objectLiteral.test.ts
- ark/type/parser/objectLiteral.ts
- ark/type/parser/shared.ts
I'm not quite done yet as there are still some non-passing tests and unanswered questions.
> feat: spread operator (...) for object literals

- ark/type/match.ts
- ark/util/functions.ts
- ark/util/hkt.ts
- ark/util/objectKinds.ts
- ark/util/records.ts
- ark/util/unionToTuple.ts
This commit removes the `Fn` utility type and replaces all of its uses with its definition, along with phasing out its custom parameters and return type utilities in favor of the lib.d.ts versions.
Causes conflicts in #904.
> refactor: remove the `Fn` utility type

- ark/attest/cache/ts.ts
The `tsconfig` config option is no longer ignored when instantiating the TypeScript environment.
Fixes https://github.com/arktypeio/arktype/issues/919
> fix(attest): Use user-provided tsconfig.json path

- ark/attest/README.md
Hey @ssalbdivad! Here's a quick fix for the attest docs. Let me know if you have any feedback.
> docs(attest): use namespace import to avoid name collision in README

- ark/dark/color-theme.json
Adds highlighting for `meta.function-call.python`.
Highlighting for `meta.function-call` was removed [removed in b989a6](https://github.com/arktypeio/arktype/commit/b989a609704080373f1fe14f1c1fdac5035310d7#diff-5e905b02abde283f0e8a6890c4b4e0899cf2cd86c64b5004704264e7bba17a74L9), presumably to fix a highlight bug in js/ts, but this broke the highlighting for Python.
Adding `meta.function-call.python` means Python can keep the function call highlighting, whilst not conflicting with the js/ts highlighting.
> fix(ArkDark): Add `meta.function-call.python` highlighting

- .changeset/healthy-numbers-play.md
- .changeset/little-icons-impress.md
- ark/attest/__tests__/snapPopulation.test.ts
- ark/schema/ast.ts
- ark/schema/node.ts
- ark/schema/predicate.ts
- ark/schema/roots/intersection.ts
- ark/schema/roots/morph.ts
- ark/schema/roots/root.ts
- ark/schema/roots/union.ts
- ark/schema/shared/traversal.ts
- ark/type/CHANGELOG.md
- ark/type/__tests__/narrow.test.ts
- ark/type/__tests__/pipe.test.ts
- ark/type/__tests__/realWorld.test.ts
- ark/type/__tests__/traverse.test.ts
- ark/type/package.json
- ark/type/type.ts
- ark/util/package.json
- Fix a crash when piping to nested paths (see https://github.com/arktypeio/arktype/issues/968)
- Fix inferred input type of `.narrow` (see https://github.com/arktypeio/arktype/issues/969)
- Throw on a pipe between disjoint types, e.g.:
```ts
// Now correctly throws ParseError: Intersection of <3 and >5 results in an unsatisfiable type
const t = type("number>5").pipe(type("number<3"))
// Previously returned a Disjoint object
```
- Mention the actual value when describing an intersection error:
```ts
const evenGreaterThan5 = type({ value: "number%2>5" })
const out = evenGreaterThan5(3)
if (out instanceof type.errors) {
/*
value 3 must be...
• a multiple of 2
• at most 5
*/
console.log(out.summary)
}
// was previously "value must be..."
```
Thanks …
> fix consecutive narrow inference, nested pipes

- ark/type/__tests__/keywords.test.ts
- ark/type/keywords/format.ts
Adds `format.capitalize` which is a non-JavaScript-native keyword.
> feat: add `format.capitalize`

- ark/type/__tests__/keywords.test.ts
- ark/type/keywords/format.ts
Adds support for [`string.toWellFormed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed) as `format.wellFormed`
> feat: add `format.wellFormed`

- ark/type/__tests__/keywords.test.ts
- ark/type/keywords/format.ts
Adds `format.normalize`.
As discussed in https://github.com/arktypeio/arktype/issues/1073 we should expand this with all options (with backwards compatibility) in the future.
> feat: add `format.normalize`

- ark/attest/assert/chainableAssertions.ts
- ark/attest/cache/ts.ts
This PR removes the code formatting type strings for the `typescript.json` cache file (in `ark/attest/cache/ts.ts` `getStringifiableType`), and instead applies formatting on an as-needed basis when `toString` is called on object types (relevant function in `ark/attest/assert` `chainableAssertions`).
This change reduces test run time substantially, cutting ~4.08 s from a ~11.4 s process.
Relevant PR: https://github.com/arktypeio/arktype/issues/1065
> perf(attest): lazy formatting for type strings

- ark/type/__tests__/string.test.ts
- ark/type/parser/string/shift/operator/operator.ts
- ark/type/parser/string/shift/scanner.ts
Inserting newlines *after* an operator (`a | \n b`), currently works, but placing the newline before it (`a \n | b`) fails, because the dynamic operator parsing code is hardcoded to only skip spaces. (The static parser *did* correctly check for any whitespace here.) In addition, the list of terminating characters needs to include non-space whitespace, otherwise the newlines can end up as part of the parsed type.
> fix: accept newlines before an operator

- ark/type/__tests__/dateLiteral.test.ts
Latest arktype version has a regression where using a morph on a `Date` type ends up with:
```
TypeError: Method Date.prototype.toISOString called on incompatible receiver [object Object]
```
I think this is related to deep cloning? PR adds a test to demonstrate.
> test: add cloned Date test

- ark/repo/scratch.ts
- ark/type/__tests__/objectLiteral.test.ts
- ark/type/parser/definition.ts
- ark/util/generics.ts
- ark/util/records.ts
> fix: avoid reducing some optional object types to base object

- ark/attest/tsVersioning.ts
```
Error: TypeScript version typescript-eslint specified in D:\<my project>/package.json must be installed at D:\<my project>/node_modules/typescript-eslint
```
> attest: fix typescript-eslint be recognized as typescript

- .github/ISSUE_TEMPLATE/bug_report.md
Makes it more likely that issue reports have useful environment information 🙂
> repo: add envinfo suggestion to bug report template

- ark/type/__tests__/keywords/string.test.ts
- ark/type/keywords/string/base64.ts
- ark/type/keywords/string/string.ts
This PR adds simple regex-based keywords for `string.base64` and `string.base64url`.
* The `registry` test currently fails due to a bug in the main repo for `@ark/util`. I've confirmed that fixing this locally causes all checks and tests to pass.
Notes:
The regular expression used does not allow for whitespace as it isn't allowed by the [Base64 specification](https://datatracker.ietf.org/doc/html/rfc4648). However, many common Base64 implementations will implicitly ignore whitespace in the string, including `atob` and `Buffer.from(..., 'base64')`. Should this implementation strictly adhere to the specification or allow "incorrect" Base64 strings with whitespace in them?
> feat: Added string.base64 and string.base64url

- ark/type/methods/base.ts
- ark/type/methods/morph.ts
- ark/type/methods/object.ts
- ark/type/type.ts
> feat: add JSDoc for common Type methods

- ark/attest/tsVersioning.ts
- ark/repo/build.ts
- ark/repo/scratch.ts
- ark/schema/shared/intersections.ts
- ark/type/__tests__/pipe.test.ts
> fix: preserve morphs on some piped properties

- ark/schema/shared/errors.ts
- ark/schema/shared/traversal.ts
- ark/schema/shared/utils.ts
> perf: optimize traversals with a very large number of errors

- ark/docs/astro.config.js
The sidebar currently redirects to https://arktype.io/string#literals, however the correct link is https://arktype.io/primitives/#string/literals
> Fix broken link to string literals docs page

- ark/docs/src/content/docs/objects.mdx
Based on this comment: https://github.com/arktypeio/arktype/issues/518#issue-1414353250
Added because I found the lack of a standard date format in the examples confusing, forgetting that this is just how Date works.
> Clarify date string literals being passed to Date in objects.mdx

- ark/docs/content/docs/scopes/index.mdx
The scope example in the docs imported `type` instead of `scope`.
> docs: fix scope example import

- ark/docs/app/(home)/layout.tsx
Hello, title page is missing on the main page and as such my browser window is simply titled `Mozilla Firefox`.  
This change adds a title tag in HomeLayout which sets it only for the main page. Documentation page titles are unchanged.
> docs: add main page title

- ark/docs/components/InstallationTabs.tsx
Yarn uses `add` instead of `install` to add a package.
> fix: Yarn install command corrected

- ark/docs/content/docs/faq.mdx
Document that async morphs are not supported and it is intentional since the use cases aren't compelling enough yet and it would add a lot of complexity to the codebase
> docs: document current stance on async morphs

- ark/util/clone.ts
Ignore accessor properties to prevent assigning a “value” field when a getter or setter exists
This is my first pr, so please tell me if i missed someting.
This pr prevents the error "TypeError: Invalid property. 'value' present on property with getter or setter." when trying to parse an object with a getter or setter.
As an example, you would need to pass process.env with an spread operator({ process.env }) so it could be validated and not throw an error by the lib. With this fix, now it can be validated correctly without the spread operator.
I think the test "can clone process.env" at [clone.test.ts](../blob/main/ark/type/__tests__/clone.test.ts) might need to be changed to reflect this new behavior.
> fix: avoid cloning accessor properties

- ark/attest/CHANGELOG.md
- ark/attest/README.md
- ark/attest/__tests__/assertions.test.ts
- ark/attest/assert/chainableAssertions.ts
- ark/attest/cache/utils.ts
- ark/attest/cache/writeAssertionCache.ts
- ark/attest/package.json
- ark/fs/package.json
- ark/repo/scratch.ts
- ark/schema/package.json
- ark/type/CHANGELOG.md
- ark/type/__tests__/objects/namedKeys.test.ts
- ark/type/package.json
- ark/type/parser/objectLiteral.ts
- ark/util/package.json
- ark/util/registry.ts
Addresses #1294
```ts
const t = type({
/** FOO */
foo: "string",
/** BAR */
bar: "number?"
})
const out = t.assert({ foo: "foo" })
// go-to definition will now navigate to the foo prop from the type call
// hovering foo now displays "FOO"
console.log(out.foo)
// go-to definition will now navigate to the bar prop from the type call
// hovering bar now displays "BAR"
// (the ? must be in the value for this to work)
console.log(out.bar)
```
> preserve jsdoc and navigation for homomorphic keys

- ark/schema/__tests__/jsonSchema.test.ts
- ark/schema/roots/union.ts
Slight improvement in json-schema output for boolean types:
Before:
```ts
import {type} from 'arktype'
type('boolean').toJsonSchema() // {anyOf: [{type: 'boolean'}]}
```
After:
```ts
import {type} from 'arktype'
type('boolean').toJsonSchema() // {type: 'boolean'}
```
I just moved the existing special case for booleans a little earlier. There might be a better spot for it though?
> simplify boolean json schema output

- ark/docs/content/docs/primitives/index.mdx
This link was missing an id so the sidebar didn't link to this section properly.
> add docs link for number keywords

- ark/attest/package.json
- ark/fs/package.json
- ark/schema/package.json
- ark/schema/refinements/pattern.ts
- ark/schema/roots/intersection.ts
- ark/schema/shared/implement.ts
- ark/type/CHANGELOG.md
- ark/type/__tests__/enclosed.test.ts
- ark/type/__tests__/pipe.test.ts
- ark/type/__tests__/realWorld.test.ts
- ark/type/__tests__/regex.test.ts
- ark/type/__tests__/type.test.ts
- ark/type/package.json
- ark/util/package.json
- ark/util/registry.ts
```ts
const t = type(/^a.*z$/)
// old: string /^a.*z$/
// new: /^a.*z$/
console.log(t.expression)
```
> improve .expression for regex constraints

- ark/attest/__tests__/benchExpectedOutput.ts
- ark/type/__tests__/match.bench.ts
- ark/type/__tests__/nary.test.ts
- ark/type/__tests__/operator.bench.ts
- ark/type/nary.ts
fixes: #1422 
- Added scope `$` to all nary type inference. 
- added n-ary (1-16) with scope tests and added normal n-ary test variants (1-16) where possible
> fix nary type inference for scopes

- ark/docs/content/docs/intro/setup.mdx
The JetBrains IDE plugin as of now already offers similar syntax highlighting to the VsCode plugin.
There are also more features planned around code completion suggestions, go to definition for type aliases and quick docs.
> docs: add JetBrains IDE plugin

- ark/json-schema/package.json
- ark/json-schema/scope.ts
This PR enables jit for `@ark/json-schema`
It was previously disabled during development as a workaround for #1188, but that has now been solved.
I've confirmed that the library works with jit by adding a temporary script and running it & also by running the `@ark/json-schema` unit tests.
> Re-enable jit for @ark/json-schema

- ark/docs/app/global.css
> fix docs popover
